name: md5_file_checksum
description: Flutter plugin to calculate a file checksum as MD5 hash, using a platform native implementation.
version: 1.1.0
repository: https://github.com/albemala/md5_file_checksum

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.7.12"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  pigeon: ^10.0.0
  crypto: ^3.0.2

flutter:
  plugin:
    platforms:
      android:
        package: me.albemala.md5_file_checksum
        pluginClass: Md5FileChecksumPlugin
      ios:
        pluginClass: Md5FileChecksumPlugin
